### ISSUE TITLE
FEATURE: Merge luci-app-advanced-reboot into Althea-dash. So you can reboot, shutdown, and decide which partition to boot

### ISSUE THREAD

**Issue by jphein** [althea-net/althea-firmware#71]
luci-app-advanced-reboot provides a way to deal with dual firmware routers.

**Comment by thosmos** [comment]
luci is not enabled on althea images.  You can switch partitions from the command line:

This will tell you which partition (1 or 2) that is currently booted. 
```
/usr/sbin/fw_printenv -n boot_part
```
This will tell it which partition to use next time:
```
/usr/sbin/fw_setenv boot_part 2
```
